name: atlas
version: "0.4.0"
config-version: 2

profile: atlas

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  atlas:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
